# Generated by Django 5.2.9 on 2025-12-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('outcome', models.TextField()),
                ('total_hours', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADED', 'Uploaded'), ('DISAPPROVED', 'Disapproved'), ('APPROVED', 'Approved'), ('HOURS_SUBMITTED', 'Hours Submitted'), ('VERIFIED', 'Verified')], default='NOT_UPLOADED', max_length=20)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('hours_completed', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseassignment')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.topic')),
            ],
            options={
                'unique_together': {('topic', 'course_assignment')},
            },
        ),
    ]
